- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
    check:
      jobs:
        - python-saharaclient-scenario
        - python-saharaclient-tempest
    gate:
      queue: sahara
      jobs:
        - python-saharaclient-scenario
        - python-saharaclient-tempest
    experimental:
      jobs:
        - openstack-tox-pypy

- job:
    name: python-saharaclient-scenario
    description: |
      Run scenario tests for Sahara against python-saharaclient changes.
    parent: sahara-tests-scenario
    required-projects:
      - openstack/python-saharaclient
    vars:
      devstack_localrc:
        LIBS_FROM_GIT: python-saharaclient

- job:
    name: python-saharaclient-tempest
    description: |
      Run Tempest tests from the Sahara plugin against python-saharaclient
      changes.
    parent: sahara-tests-tempest
    required-projects:
      - openstack/python-saharaclient
    vars:
      devstack_localrc:
        LIBS_FROM_GIT: python-saharaclient
