- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - release-notes-jobs
      - openstackclient-plugin-jobs
    post:
      jobs:
        - openstack-tox-cover
    gate:
      queue: sahara
    experimental:
      jobs:
        - openstack-tox-pypy
