- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-wallaby-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
    check:
      jobs:
        - python-saharaclient-scenario
        - python-saharaclient-scenario-v2
        - python-saharaclient-tempest
        - python-saharaclient-tempest-v2
    gate:
      queue: sahara
      jobs:
        - python-saharaclient-scenario
        - python-saharaclient-scenario-v2
        - python-saharaclient-tempest
        - python-saharaclient-tempest-v2

- job:
    name: python-saharaclient-scenario
    description: |
      Run scenario tests for Sahara against python-saharaclient
      changes.
    parent: sahara-tests-scenario
    required-projects:
      - openstack/python-saharaclient

- job:
    name: python-saharaclient-scenario-v2
    description: |
      Run scenario tests for Sahara on API v2 against python-saharaclient
      changes.
    parent: sahara-tests-scenario-v2
    required-projects:
      - openstack/python-saharaclient

- job:
    name: python-saharaclient-tempest
    description: |
      Run Tempest tests from the Sahara plugin against python-saharaclient
      changes.
    parent: sahara-tests-tempest
    required-projects:
      - openstack/python-saharaclient

- job:
    name: python-saharaclient-tempest-v2
    description: |
      Run Tempest tests from the Sahara plugin on API v2 against
      python-saharaclient changes.
    parent: sahara-tests-tempest-v2
    required-projects:
      - openstack/python-saharaclient
